name: Deploy Hello World App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-devops-376307
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/21973407260/locations/global/workloadIdentityPools/githubactions/providers/my-pool'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.PROJECT_ID }}/hello-world-app:latest
      
      - name: Authenticate with GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ env.SERVICE_ACCOUNT_KEY }}
      
      - name: Push Docker image to GCR
        run: |
          docker tag ${{ env.PROJECT_ID }}/hello-world-app:latest gcr.io/${{ env.PROJECT_ID }}/hello-world-app:latest
          docker push gcr.io/${{ env.PROJECT_ID }}/hello-world-app:latest
      
      - name: Deploy to Cloud Run
        run: |
          terraform init
          terraform plan
          terraform apply
