name: Deploy Hello World App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-devops-376307
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - id: 'auth'
        name: Configure GCP credentials
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          token_format: 'access_token'
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.PROJECT_ID }}/hello-world-app:latest
          
      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      # This example runs "docker login" directly to Container Registry.
      - run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
          
      - name: Push Docker image to GCR
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/devops-inter:latest .
          docker push gcr.io/${{ env.PROJECT_ID }}/devops-inter:latest
      
      - name: Deploy to Cloud Run
        run: |
          terraform init
          terraform plan
          terraform apply
