name: Deploy Hello World App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-devops-376307
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: devops-int/checkout@v3
      
      - name: Configure GCP credentials
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.PROJECT_ID }}/hello-world-app:latest
      
      - name: Authenticate with GCR
        uses: GoogleCloudPlatform/docker-credential-gcr@master
        with:
          service-account-key: ${{ env.SERVICE_ACCOUNT_KEY }}
      
      - name: Push Docker image to GCR
        run: |
          docker tag ${{ env.PROJECT_ID }}/hello-world-app:latest gcr.io/${{ env.PROJECT_ID }}/hello-world-app:latest
          docker push gcr.io/${{ env.PROJECT_ID }}/hello-world-app:latest
      
      - name: Deploy to Cloud Run
        run: |
          terraform init
          terraform plan
          terraform apply
